// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktp0n51PC82qAdIGfDNcg9aUHE_jAPtg',
    appId: '1:946617176434:web:29ab9fc1b67f34d0cfcdeb',
    messagingSenderId: '946617176434',
    projectId: 'spotify-0707',
    authDomain: 'spotify-0707.firebaseapp.com',
    storageBucket: 'spotify-0707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6SiA47Hoi1GciGCRiq5_fE-pE43OxEK4',
    appId: '1:946617176434:android:49f273181f846655cfcdeb',
    messagingSenderId: '946617176434',
    projectId: 'spotify-0707',
    storageBucket: 'spotify-0707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_90vbEpnpUDGLmt18CfuRXRjwf9FBcCY',
    appId: '1:946617176434:ios:8bd657e81d6d5e82cfcdeb',
    messagingSenderId: '946617176434',
    projectId: 'spotify-0707',
    storageBucket: 'spotify-0707.firebasestorage.app',
    iosBundleId: 'com.example.sporifyyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_90vbEpnpUDGLmt18CfuRXRjwf9FBcCY',
    appId: '1:946617176434:ios:8bd657e81d6d5e82cfcdeb',
    messagingSenderId: '946617176434',
    projectId: 'spotify-0707',
    storageBucket: 'spotify-0707.firebasestorage.app',
    iosBundleId: 'com.example.sporifyyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCktp0n51PC82qAdIGfDNcg9aUHE_jAPtg',
    appId: '1:946617176434:web:73b8fa57e4551e6fcfcdeb',
    messagingSenderId: '946617176434',
    projectId: 'spotify-0707',
    authDomain: 'spotify-0707.firebaseapp.com',
    storageBucket: 'spotify-0707.firebasestorage.app',
  );
}
